apiVersion: v1
kind: Service
metadata:
  name: secure-k8s-api
  namespace: secure-k8s

spec:
  type: ClusterIP

  selector:
    app: secure-k8s-api

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000