name: Secure Kubernetes Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read        

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: |
          node src/server.js > app.log 2>&1 &
          echo $! > app.pid

      - name: Health check
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost:3000/health; then
              exit 0
            fi
            sleep 1
          done

          cat app.log
          exit 1

      - name: Stop application
        if: always()
        run: |
          if [ -f app.pid ]; then
            kill $(cat app.pid) || true
          fi

  sast:
    name: SAST - CodeQL
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v4


  sca:
    name: SCA - Dependency Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Dependency vulnerability scan
        run: npm audit --audit-level=high


  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs : [ci, sast, sca]

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t secure-k8s-api:${{ github.sha }} .

      - name: Save Docker image
        run: docker save secure-k8s-api:${{ github.sha }} -o secure-k8s-api.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: secure-k8s-api-image
          path: secure-k8s-api.tar
          retention-days: 1

  trivy:
    name: Trivy - Container Vulnerability Scan
    runs-on: ubuntu-latest
    needs: docker-build

    permissions:
      contents: read

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v5
        with:
          name: secure-k8s-api-image

      - name: Load Docker image
        run: docker load -i secure-k8s-api.tar

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: secure-k8s-api:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

  sbom:
    name: SBOM - Generate Software Bill of Materials
    runs-on: ubuntu-latest
    needs: docker-build

    permissions:
      contents: read

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v5
        with:
          name: secure-k8s-api-image

      - name: Load Docker image
        run: docker load -i secure-k8s-api.tar

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: secure-k8s-api:${{ github.sha }}
          format: cyclonedx-json
          output-file: sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-k8s-api-sbom
          path: sbom.json      

  publish:
    name: Publish Image to GHCR
    runs-on: ubuntu-latest
    needs: [trivy, sbom]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v5
        with:
          name: secure-k8s-api-image

      - name: Load Docker image
        run: docker load -i secure-k8s-api.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: |
          docker tag \
            secure-k8s-api:${{ github.sha }} \
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Push image
        run: |
          docker push \
            ghcr.io/${{ github.repository }}:${{ github.sha }}